### ISSUE TITLE
To port tweening system from HaxeFlixel

### ISSUE THREAD

**Issue by devolonter** [devolonter/flixel-monkey#46]

**Comment by Beeblerox** [comment]
This isn't hard thing. Main classes you should look into are: FlxG, FlxGame, FlxGroup, FlxBasic and all classes in 'org.flixel.tweens' package.
If you'll have some questions then you can mail me at zaphy[at]yandex.ru 
Good luck with it :)

**Comment by devolonter** [comment]
Thank you! And many thanks for infromation and suggestion!
