### ISSUE TITLE
QuickStart example failed 

### ISSUE THREAD

**Issue by henryscala** [devolonter/flixel-monkey#75]
For running the QuickStart example, I met several issues. 

First issue: I need to import the "reflection" module, otherwise, the 'GetClass("HelloWorldState")' function call will return Null. 

After fixing the first issue. I met the second issue. 

Second issue: The following error appears. I checked the document, and noticed that 'DeviceWidth' is defined in 'mojo.app' module, so I imported it in the 'flximagedata.monkey'. However, I met the third issue.

`system/flximagedata.monkey<108> : Error : Identifier 'DeviceWidth' not found`. 

Third issue: The following error appears after fixing the Second issue. I cannot find where the defect locates. I am a new user of monkey language, and the issues are what I observed. I'm not 100% sure they are real issues. 

`MonkeyXFree84f/modules/monkey/stack.monkey<26> : Error : Arrays cannot be compared.`

**Comment by devolonter** [comment]
Hello and thanks for report! Should be fixed now. Please see updated QuckStart sample in readme

**Comment by henryscala** [comment]
I updated and tried the QuickStart sample, and it works without the former errors.
Thank you very much! 
And I think the project is very useful.
